# Generated by Django 4.0.3 on 2023-06-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hats_rest', '0002_remove_locationvo_section_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationvo',
            name='href',
            field=models.CharField(blank=True, max_length=300, unique=True),
        ),
    ]
