# Generated by Django 4.0.3 on 2023-06-02 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hats_rest', '0004_alter_locationvo_href'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationvo',
            old_name='href',
            new_name='import_href',
        ),
    ]
